### ISSUE TITLE
Error when I try to use the example

### ISSUE THREAD

**Issue by ghost** [vinsfortunato/hid4flutter#1]
Hi there !

When I use your example, I have an error like that :
`flutter: Error getting connected devices: LateInitializationError: Field '_instance@64480452' has not been initialized.` 

Flutter : `3.16.5`
Dart : `3.2.3`

And I'm on Linux (Ubuntu 23.10) btw ^^.

Do you have any idea what's going on?

**Comment by vinsfortunato** [comment]
It seems that the Linux backend doesn't load the native library correctly.

On your Linux system try to install hidapi with:

```
sudo apt-get install libhidapi-hidraw0
```

Then reopen the example.

Currently you need to have `libhidapi` installed on Linux.

I'm trying to compile `hidapi` with the flutter application instead of using the one installed on the system. That is how it works on Windows but can't get it to work also on Linux.
This way there will be no need to install it manually.

Let me know if installing it manually fixes your problem!

**Comment by vinsfortunato** [comment]
It seems that the Linux backend doesn't load the native library correctly.

On your Linux system try to install hidapi with:

bash
```
sudo apt-get install libhidapi-hidraw0
```

Then reopen the example.

Currently you need to have `libhidapi` installed on Linux.

I'm trying to compile `hidapi` with the flutter application instead of using the one installed on the system. That is how it works on Windows but can't get it to work also on Linux.

This way there will be no need to install it manually.

Let me know if installing hidapi manually fixes your problem!

**Comment by ghost** [comment]
That's it. Thanks ^^.

**Comment by vinsfortunato** [comment]
Duplicate of #2
